// AUTO-GENERATED by backend/generate-seed.mjs — do not edit by hand.
// Field-appropriate "Recommended Organizations" per department, used to guarantee every
// professor (including newly added ones) lists >= 6 real companies.
export const DEPARTMENT_COMPANIES: Record<string, string[]> = {
  "dept_ce": [
    "L&T Construction",
    "AFCONS Infrastructure",
    "Tata Projects",
    "Shapoorji Pallonji",
    "AECOM",
    "Jacobs",
    "WSP",
    "Arcadis",
    "Hindustan Construction Company",
    "Tata Consulting Engineers"
  ],
  "dept_ch": [
    "Reliance Industries",
    "Indian Oil Corporation",
    "ONGC",
    "BPCL",
    "Tata Chemicals",
    "Aarti Industries",
    "UPL",
    "Pidilite Industries",
    "Linde",
    "SABIC"
  ],
  "dept_cs": [
    "Google",
    "Microsoft",
    "Amazon",
    "Adobe",
    "NVIDIA",
    "Meta",
    "Oracle",
    "TCS",
    "Infosys",
    "Uber"
  ],
  "dept_ee": [
    "Siemens",
    "ABB",
    "Schneider Electric",
    "Texas Instruments",
    "Qualcomm",
    "GE",
    "Bosch",
    "Larsen & Toubro",
    "Havells",
    "Tata Power"
  ],
  "dept_hs": [
    "Deloitte",
    "McKinsey & Company",
    "Nielsen",
    "Ipsos",
    "EY",
    "KPMG",
    "World Bank",
    "UNDP",
    "Pratham",
    "Ashoka University"
  ],
  "dept_ma": [
    "Goldman Sachs",
    "JPMorgan Chase",
    "Morgan Stanley",
    "D. E. Shaw",
    "Jane Street",
    "WorldQuant",
    "American Express",
    "Fractal Analytics",
    "Mu Sigma",
    "Indian Statistical Institute"
  ],
  "dept_me": [
    "Tata Motors",
    "Mahindra & Mahindra",
    "Maruti Suzuki",
    "Bosch",
    "Larsen & Toubro",
    "Ashok Leyland",
    "Cummins",
    "General Motors",
    "ISRO",
    "BHEL"
  ],
  "dept_mt": [
    "Tata Steel",
    "JSW Steel",
    "Hindalco",
    "Vedanta",
    "ArcelorMittal",
    "DRDO",
    "ISRO",
    "Corning",
    "Jindal Steel & Power",
    "BHEL"
  ],
  "dept_ph": [
    "ISRO",
    "DRDO",
    "BARC",
    "TIFR",
    "Intel",
    "Applied Materials",
    "Coherent",
    "Bruker",
    "Raman Research Institute",
    "CERN"
  ],
  "dept_ai": [
    "OpenAI",
    "Google DeepMind",
    "NVIDIA",
    "Microsoft",
    "Amazon",
    "Meta",
    "Adobe",
    "IBM Research",
    "Fractal Analytics",
    "Qualcomm"
  ],
  "_default": [
    "TCS",
    "Infosys",
    "Wipro",
    "Accenture",
    "Deloitte",
    "Larsen & Toubro",
    "Reliance Industries",
    "Cognizant"
  ]
};

export function withFieldCompanies(existing: string[] | string | undefined, departmentId: string, cap = 8): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  const push = (name: string) => {
    const clean = String(name || '').trim();
    const key = clean.toLowerCase();
    if (!clean || seen.has(key)) return;
    seen.add(key);
    out.push(clean);
  };
  const cur = Array.isArray(existing) ? existing : existing ? [existing] : [];
  cur.forEach(push);
  const pool = DEPARTMENT_COMPANIES[departmentId] || DEPARTMENT_COMPANIES._default;
  for (const n of pool) { if (out.length >= cap) break; push(n); }
  if (out.length < 6) for (const n of DEPARTMENT_COMPANIES._default) { if (out.length >= 6) break; push(n); }
  return out.slice(0, cap);
}
